// quotes.js

const data=[
      { q: "The only way to do great work is to love what you do.", a: "Steve Jobs" },
      { q: "In the end, we will remember not the words of our enemies, but the silence of our friends.", a: "Martin Luther King Jr." },
      { q: "The best way to predict the future is to invent it.", a: "Alan Kay" },
      { q: "Life is what happens when you're busy making other plans.", a: "John Lennon" },
      { q: "It does not matter how slowly you go as long as you do not stop.", a: "Confucius" },
      { q: "If you can dream it, you can do it.", a: "Walt Disney" },
      { q: "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well.", a: "Ralph Waldo Emerson" },
      { q: "Success is not final, failure is not fatal: It is the courage to continue that counts.", a: "Winston Churchill" },
      { q: "You miss 100% of the shots you don’t take.", a: "Wayne Gretzky" },
      { q: "Life is 10% what happens to us and 90% how we react to it.", a: "Charles R. Swindoll" },
      { q: "The best revenge is massive success.", a: "Frank Sinatra" },
      { q: "Act as if what you do makes a difference. It does.", a: "William James" },
      { q: "It always seems impossible until it’s done.", a: "Nelson Mandela" },
      { q: "Keep your face always toward the sunshine—and shadows will fall behind you.", a: "Walt Whitman" },
      { q: "You must be the change you wish to see in the world.", a: "Mahatma Gandhi" },
      { q: "To live is the rarest thing in the world. Most people exist, that is all.", a: "Oscar Wilde" },
      { q: "Good friends, good books, and a sleepy conscience: this is the ideal life.", a: "Mark Twain" },
      { q: "The only impossible journey is the one you never begin.", a: "Tony Robbins" },
      { q: "The unexamined life is not worth living.", a: "Socrates" },
      { q: "You only live once, but if you do it right, once is enough.", a: "Mae West" },
      { q: "Do not go where the path may lead, go instead where there is no path and leave a trail.", a: "Ralph Waldo Emerson" },
      { q: "Everything you can imagine is real.", a: "Pablo Picasso" },
      { q: "It is never too late to be what you might have been.", a: "George Eliot" },
      { q: "The only thing necessary for the triumph of evil is for good men to do nothing.", a: "Edmund Burke" },
      { q: "Don’t watch the clock; do what it does. Keep going.", a: "Sam Levenson" },
      { q: "The only limit to our realization of tomorrow is our doubts of today.", a: "Franklin D. Roosevelt" },
      { q: "Don’t count the days, make the days count.", a: "Muhammad Ali" },
      { q: "A person who never made a mistake never tried anything new.", a: "Albert Einstein" },
      { q: "The best time to plant a tree was 20 years ago. The second best time is now.", a: "Chinese Proverb" },
      { q: "You must do the things you think you cannot do.", a: "Eleanor Roosevelt" },
      { q: "The future belongs to those who believe in the beauty of their dreams.", a: "Eleanor Roosevelt" },
      { q: "Success usually comes to those who are too busy to be looking for it.", a: "Henry David Thoreau" },
      { q: "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.", a: "Roy T. Bennett" },
      { q: "Difficulties in life are intended to make us better, not bitter.", a: "Dan Reeves" },
      { q: "Success is not how high you have climbed, but how you make a positive difference to the world.", a: "Roy T. Bennett" },
      { q: "You are never too old to set another goal or to dream a new dream.", a: "C.S. Lewis" },
      { q: "It’s not whether you get knocked down, it’s whether you get up.", a: "Vince Lombardi" },
      { q: "If you want to go fast, go alone. If you want to go far, go together.", a: "African Proverb" },
      { q: "The only way to achieve the impossible is to believe it is possible.", a: "Charles Kingsleigh" },
      { q: "Everything has beauty, but not everyone can see it.", a: "Confucius" },
      { q: "In three words I can sum up everything I’ve learned about life: it goes on.", a: "Robert Frost" },
      { q: "It’s not what happens to you, but how you react to it that matters.", a: "Epictetus" },
      { q: "The more that you read, the more things you will know. The more that you learn, the more places you’ll go.", a: "Dr. Seuss" },
      { q: "You have as many hours in a day as Beyoncé.", a: "Unknown" },
      { q: "Success is not the key to happiness. Happiness is the key to success.", a: "Albert Schweitzer" },
      { q: "You don’t have to be great to start, but you have to start to be great.", a: "Zig Ziglar" },
      { q: "Everything you’ve ever wanted is on the other side of fear.", a: "George Addair" },
      { q: "I find that the harder I work, the more luck I seem to have.", a: "Thomas Jefferson" },
      { q: "Do one thing every day that scares you.", a: "Eleanor Roosevelt" },
      { q: "Nothing will work unless you do.", a: "Maya Angelou" },
      { q: "I am not a product of my circumstances. I am a product of my decisions.", a: "Stephen R. Covey" },
      { q: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", a: "Aristotle" },
      { q: "You become what you believe.", a: "Oprah Winfrey" },
      { q: "The best way to find yourself is to lose yourself in the service of others.", a: "Mahatma Gandhi" },
      { q: "Whether you think you can, or you think you can’t—you’re right.", a: "Henry Ford" }
    ]
  
  
  export default data;
  